# Generated by Django 3.2.19 on 2023-12-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('admin_pw', models.CharField(max_length=100)),
                ('admin_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('views', models.IntegerField()),
                ('file', models.BinaryField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=30)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shieldletter.admin')),
            ],
        ),
    ]
