# Generated by Django 3.2.19 on 2023-12-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shieldletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='admin',
            new_name='writer',
        ),
    ]
