# Generated by Django 3.2.19 on 2023-12-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldletter', '0003_rename_writer_board_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
