# Generated by Django 3.2.19 on 2023-12-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldletter', '0004_alter_board_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
