# Generated by Django 3.2.19 on 2023-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldletter', '0005_auto_20231228_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.ImageField(null=True, upload_to='upload/%Y/%m/%d'),
        ),
    ]
