# Generated by Django 3.2.19 on 2023-12-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldletter', '0006_auto_20231228_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
