# Generated by Django 3.2.19 on 2023-12-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shieldletter', '0002_rename_admin_board_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='writer',
            new_name='admin',
        ),
    ]
