# Generated by Django 3.2.19 on 2023-12-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shieldletter', '0007_auto_20231228_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
