# Generated by Django 3.2.19 on 2023-12-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shieldletter', '0007_board_no'),
        ('shieldletter', '0009_user'),
    ]

    operations = [
    ]
