# Generated by Django 3.2.19 on 2023-12-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shieldletter', '0010_merge_0007_board_no_0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
